apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: 172-net-cidr-172-net
  labels:
    fabrix.io/managed: true
    fabrix.io/source-system: nsx
    fabrix.io/original-group-name: 172-net
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
  annotations:
    fabrix.io/last-synced: 2026-03-03T22:15:36.8948471Z
    fabrix.io/nsx-group-path: /infra/domains/default/groups/172_net
spec:
  externalCidrs:
  - 172.16.100.0/24
