apiVersion: fabrix.io/v1alpha1
kind: FabrixSystemSecurityGroup
metadata:
  name: group-with-a-tag
  labels:
    fabrix.io/managed: true
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
spec:
  displayName: group-with-a-tag
  endpointIPs: []
  origin:
    system: NSX
    originatedId: Groupwithatag
  type: none
