apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: local-nets-cidr-local-nets
  labels:
    fabrix.io/managed: true
    fabrix.io/source-system: nsx
    fabrix.io/original-group-name: local-nets
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
  annotations:
    fabrix.io/last-synced: 2026-03-03T22:18:35.0930080Z
    fabrix.io/nsx-group-path: /infra/domains/default/groups/LOCAL-NETS
spec:
  externalCidrs:
  - 192.168.0.0/16
  - 10.0.0.0/8
