apiVersion: fabrix.io/v1alpha1
kind: FabrixSystemSecurityGroup
metadata:
  name: manyvms
  labels:
    fabrix.io/managed: true
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
spec:
  displayName: manyvms
  matchLabels:
    tag-1011: scope-101
  endpointIPs:
  - 10.100.200.10/32
  - 192.188.1.4/32
  origin:
    system: NSX
    originatedId: ManyVMs
  type: Mixed
