apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: natwest-sg-582-cidr-natwest-sg-582
  labels:
    fabrix.io/managed: true
    fabrix.io/source-system: nsx
    fabrix.io/original-group-name: natwest-sg-582
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
  annotations:
    fabrix.io/last-synced: 2026-03-03T22:14:32.4726902Z
    fabrix.io/nsx-group-path: /infra/domains/default/groups/natwest-sg-582
spec:
  externalCidrs:
  - 10.0.0.1/32
