apiVersion: fabrix.io/v1alpha1
kind: FabrixSystemSecurityGroup
metadata:
  name: natwest-sg-582
  labels:
    fabrix.io/managed: true
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
spec:
  displayName: natwest-sg-582
  endpointIPs:
  - 10.0.0.1/32
  origin:
    system: NSX
    originatedId: natwest-sg-582
  type: IP
