apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: parent-with-2-children-cidr-parent-with-2-children
  labels:
    fabrix.io/managed: true
    fabrix.io/source-system: nsx
    fabrix.io/original-group-name: parent-with-2-children
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
  annotations:
    fabrix.io/last-synced: 2026-03-03T22:18:35.0872676Z
    fabrix.io/nsx-group-path: /infra/domains/default/groups/Parent_with_2_children_
spec:
  externalCidrs:
  - 1.1.1.0/24
  - 2.2.2.0/24
