apiVersion: fabrix.io/v1alpha1
kind: FabrixSystemSecurityGroup
metadata:
  name: vm-subnet-group
  labels:
    fabrix.io/managed: true
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
spec:
  displayName: vm-subnet-group
  endpointIPs:
  - 10.100.201.0/24
  origin:
    system: NSX
    originatedId: VMSubnetGroup
  type: IP
