apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: vm-subnet-group-cidr-vmsubnetgroup
  labels:
    fabrix.io/managed: true
    fabrix.io/source-system: nsx
    fabrix.io/original-group-name: vm-subnet-group
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
  annotations:
    fabrix.io/last-synced: 2026-03-03T22:18:35.0394254Z
    fabrix.io/nsx-group-path: /infra/domains/default/groups/VMSubnetGroup
spec:
  externalCidrs:
  - 10.100.201.0/24
