apiVersion: fabrix.io/v1alpha1
kind: FabrixSystemSecurityGroup
metadata:
  name: vms-in-group
  labels:
    fabrix.io/managed: true
    fabrix.io/datasource-id: 044b1ddf-ce50-4a2c-badc-eaff6750f2db
spec:
  displayName: vms-in-group
  endpointIPs: []
  origin:
    system: NSX
    originatedId: VMs_in_Group
  type: none
